### ISSUE TITLE
.func generates wrong value for label for unsp target

### ISSUE THREAD

**Issue by pulkomandy** [mikeakohn/naken_asm#106]
Hello,

The .func directive appears to generate symbols with values in bytes even for the unsp CPU, when the value should be in 16-bit words instead.

Test case:

    .org 0x4000
    .func foo
    bar:
    .endf

Expected value for foo should be 0x4000, but it ends up being 0x8000.
Value for bar is correct.

**Comment by mikeakohn** [comment]
I pushed an update.. should be good now. Thanks for letting me know! :)
