### ISSUE TITLE
make testing broken

### ISSUE THREAD

**Issue by codisto** [mikeakohn/naken_asm#126]
I have just build on my Devuan daedalus linux naken_asm. I want it to use for msp430, msp-exp430g2. 
On fresh download,
 ./configure; make; make test; make install:
everythig ok, but

**make testing**  return

make: *** No rule to make target **'launchpad_blink.asm'**, needed by 'testing'.  Stop.

I think that the target testing and msp430x are needless, because the source is not gcc-msp430 assembler compatible.

**Comment by mikeakohn** [comment]
That was for my own use. I can rename if you like.

**Comment by mikeakohn** [comment]
And done! :)

**Comment by codisto** [comment]
Thank you
