### ISSUE TITLE
Impossible compare code in tokens.cpp

### ISSUE THREAD

**Issue by dlkeng** [mikeakohn/naken_asm#136]

**Comment by dlkeng** [comment]
In common/tokens.cpp, the following lines test for impossible condition to occur:
Line 93: ```if ((*s == 'h' && *s =='H') && prefixed == 1) { return -1; }```
Line 160: ```if ((*s == 'b' && *s =='B') && prefixed == 1) { return -1; }```

*s can never be both 'h' and 'H' at the same time
*s can never be both 'b' and 'B' at the same time

**Comment by mikeakohn** [comment]
Should be fixed. Thanks!
