### ISSUE TITLE
Evaluation of immediate

### ISSUE THREAD

**Issue by ofosos** [mikeakohn/naken_asm#17]
Hi,
I'm trying to assemble something like

.macro(usec)
MOV #(((usec * MCLK) -2) /3),X
.endm

When I use this I get a

Error: No matching ')' at ../foobar.asm:xx

Any way to work around this?

**Comment by mikeakohn** [comment]
I think what you want is:

.macro macro_name(usec)
MOV #(((usec * MCLK) -2) /3),X
.endm

Which CPU are you trying to assemble this on?

**Comment by ofosos** [comment]
On the MSP430. Dang thats a typo on my side, your snippet isn't working either.

**Comment by mikeakohn** [comment]
I kind of figured mine wasn't working either.  Either way, the problem should be fixed now.

**Comment by mikeakohn** [comment]
Forgot to thank you for reporting the problem btw... thanks :).
