### ISSUE TITLE
Include generator for msp430 doesn't work

### ISSUE THREAD

**Issue by kryksyh** [mikeakohn/naken_asm#19]
Hi. 
I have some trouble generating include for msp430fr5969 using latest gcc msp430 include. There is no register addresses in the output (no wdtctl, padir etc).

Any suggestions?

Perhaps I should fix script with some python magic.

**Comment by kryksyh** [comment]
Nevermind, it works fine with older version of gcc includes.

**Comment by mikeakohn** [comment]
If you can fix the includes with some Python magic, let me know and I can include it with naken_asm.  There are a couple of others who converted all of the MSP430 includes from either gcc or TI into a format that naken_asm can use.  One of them has all the includes on github...
