### ISSUE TITLE
strange bit in jmp opcode

### ISSUE THREAD

**Issue by hosewiejacke** [mikeakohn/naken_asm#20]
Given this code:

    loop: jmp loop

Assembling by hand:

* `jmp` gives *3Cxx* (according to slau144j, page 62)
* `loop` gives *-1* (jump back 1 word)
* combining *3Cxx* and 9 bits from *-1* gives **3DFF**

Assembling with naken_asm:

* gives **3FFF** [1]

Who is wrong?

[1]  The full Intel HEX is:

    :02000000FF3FC0
    :00000001FF

EDIT:

* changed label from `l` to `loop` to avoid similarity with digit 1
* added page number for slau144j
* slightly improved layout and markup

**Comment by mikeakohn** [comment]
You're talking about MSP430, right?  I think jmp 1 is illegal.  When I try and assemble that with naken_asm I get an error as I would expect.  What's your .org on this also?

**Comment by hosewiejacke** [comment]
> You're talking about MSP430, right?

Yes. I forgot naken_asm supports almost any architecture under the sun nowadays.

> I think jmp 1 is illegal.

Sorry for choosing a letter that looks like a digit. I updated the example.

> What's your .org on this also?

There's no .org. I didn't test it on hardware.

**Comment by mikeakohn** [comment]
I got almost all of my information from this page:

https://en.wikipedia.org/wiki/TI_MSP430

this page says JMP is 001111 and a 10 bit offset.  jmp to start should be an offset of -2 bytes (-1 words.. or 1111111111)... so I believe 0011111111111111 is correct and the opcode should be 0x3ffff.

**Comment by hosewiejacke** [comment]
Thanks. I just looked at the Family User's Guides for

* MSP430x4xx (slau056l, page 3-74)
* MSP430FR4xx and MSP430FR2xx (slau445f, page 172)

and the opcode for jmp is 3Cxx there. I guess it doesn't matter because the 1 bit is a don't-care.

**Comment by hosewiejacke** [comment]
I made a mistake in the calculation above. The jump destination has 10 bits instead of 9.
Sorry.

**Comment by mikeakohn** [comment]
I'd much rather getting a bug report like this than getting none at all.  If someone finds an issue (or has an idea how to improve the program) but doesn't bother to let me know, I have a harder time improving the code.  Plus, this also lets me know people have an interest in the assembler which makes me happy.. :)

So thanks for filing this and please let me know if you find anything else...
