### ISSUE TITLE
Bug in 6502 simulator accumulator shift instructions

### ISSUE THREAD

**Issue by larsbrinkhoff** [mikeakohn/naken_asm#32]
The 6502 simulator shift instructions seem strange.  There is a check for `mode == 4` which makes the instructions operate on the accumulator.  However, mode 4 is OP_INDEXED8_X.  I believe the check should be `mode == OP_NONE` instead.

**Comment by mikeakohn** [comment]
Nice find and thanks for the fix.  I'll go ahead and close this.
