### ISSUE TITLE
Two naken_util issues

### ISSUE THREAD

**Issue by zcsahok** [mikeakohn/naken_asm#39]
Two issues I came across using naken_util.

1) b/wprint don't consider end range, they always print 128 bytes.
Looks like a bug in naken_util.c
```
336:  if (start <= end) { end = start + 128; }
376:  if (start <= end) { end = start + 128; }
```

2) clear gives a strange response.
```
stopped> clear z
Flag r z set. 
```
Bug on line 1205 in naken_util.c

**Comment by mikeakohn** [comment]
These should be fixed.  Thanks again for finding them and please let me know if you find any more.
