### ISSUE TITLE
STM8 Instruction "LDF ([$0000.e],X),A" not recognized

### ISSUE THREAD

**Issue by fdx1601** [mikeakohn/naken_asm#44]
Hi, after playing around with the STM8 core recently, I stumbled over an issue with the LDF instruction.

It seems that the assembler truncates addresses below $100 and then accuses illegal addressing mode.

`LDF ([$0010.e],X),A    ; does not work`
`LDF ([$0100.e],X),A    ; does work`

I think the first variant should be valid too and generating the corresponding opcodes manually via the .db directive the instruction executes fine on the real device.

Regards.

**Comment by mikeakohn** [comment]
First commit fixes the error and the second makes a check to make sure the address is in range.  Can you check to make sure this fixes the issue?

Thanks for letting me know about this.. and please let me know if anything else doesn't work right.

**Comment by fdx1601** [comment]
Hi!

Thanks for the corrections. I wrote a small test routine and it works now as expected.

Test Code:
```
```

And here ist the monitor's output before and after running the Test Code:
```
>d
Enter Lowest  Address: 00:0400
Enter Highest Address: 00:040F

00:0400 FC 81 FF 80 B7 00 DF 00 FE 02 FF 00 FF 00 F7 60

>d
Enter Lowest  Address: 00:0400
Enter Highest Address: 00:040F

00:0400 41 42 43 80 B7 00 DF 00 FE 02 FF 00 FF 00 F7 60
```

Regards!

**Comment by fdx1601** [comment]
Forgot to close the issue in my previous post ;-)

**Comment by mikeakohn** [comment]
Cool.. thanks for the help! :)  Again, let me know if you find anything else...
