### ISSUE TITLE
6502 break_io support crashes simulator

### ISSUE THREAD

**Issue by NullMember** [mikeakohn/naken_asm#48]
Some OP_ADDRESS8 instructions with 0x00 address which writes back to memory are crashing simulator. In this case these instructions are:
> ASR, ROL, LSR, ROR, STY, STA, STX, DEC and INC

This problem only occurs when simulator started without `-run` argument. When `-run` used executing done succesfully (cycle count is right). Removing `-break_io` code from WRITE_RAM macro is resolved problem but I can't find another solution.

**Comment by mikeakohn** [comment]
Is it actually crashing, or just exiting for no apparent reason?

**Comment by mikeakohn** [comment]
I believe this is fixed.
