### ISSUE TITLE
Feature idea: dumpram while simulation running

### ISSUE THREAD

**Issue by NullMember** [mikeakohn/naken_asm#58]
Hi
I'm writing new 6502 program and i need to see RAM changes while program running. Stopping and printing RAM is not efficient. While playing with naken_util I see dumpram option but it is not implemented in 6502 simulation. I've imlemented it but it is not working like what I expected. I thought it's dumping RAM during simulation running. So I wrote some changes and now I'm calling simulate_dumpram function in simulate_run. Here is what it looks like

![SmartSelect_20190309-143208_Chrome](https://user-images.githubusercontent.com/10081908/54071150-f88d5a00-4279-11e9-94e0-64f9c3059e68.jpg)

I can make PR if anyone want to see how I implemented it. I will like to see suggestions of implementation also.

**Comment by mikeakohn** [comment]
So you want a constant dump of RAM while the simulator is running?  The 6502 can address 64k of RAM, how would the simulator know what addresses to constantly dump?

**Comment by NullMember** [comment]
User need to be write "dumpram startaddress-endaddress". In this example I wrote "dumpram 0x00-0x20" before running simulator to dump between these addresses
