### ISSUE TITLE
THUMB fails assembling "MOV R1,R2" instruction

### ISSUE THREAD

**Issue by fdx1601** [mikeakohn/naken_asm#61]
Hi!

When trying to transfer one register into another via the `MOV` instruction, the assembler complains giving this error:

```
Error: Unknown operands combo for 'MOV' at src/main.asm:211
```

where the corresponding source code looks like this:

```
                    MOV     R2,R1
```

BTW Currently I am using PUSH/POP instruction to get around this issue.

Regards.

**Comment by mikeakohn** [comment]
That mov instruction is invalid.  But there is an alias for it for add r2, r1, #0.  The assembler will create that alias for you.

**Comment by fdx1601** [comment]
Ok, that will do the trick.
