### ISSUE TITLE
RISC-V: boundchecking with immediates

### ISSUE THREAD

**Issue by ThomasAusNRW** [mikeakohn/naken_asm#79]
I've made some first steps with RISC-V assembly and get some trouble with immediates:

Immediates values are 12 bit wide, but it's not possible without an error-message to assemble instructions like

addi x1, x2, 0xff8

which should be interpreted as -8 by sign-extension. But all I got is an bound-check-error. IMHO there is no need for an error-message. It can result in a warning, not an error.

Regards, Thomas

**Comment by mikeakohn** [comment]
I did this because I thought it would confuse people who might not realize it sign extends.  If you really want I can remove it.
