### ISSUE TITLE
Macro declaration offsets line numbers

### ISSUE THREAD

**Issue by abe-k** [mikeakohn/naken_asm#8]
Following a macro declaration, line numbers reported in error messages will be one less than correct (cumulative with the number of declarations). For example,
````
.macro test
.endm

error
````
will produce the error message
````
Error: Unknown instruction 'error' at filename:3
````
despite `error` being on line 4. This does not depend on the contents of the macro.

**Comment by mikeakohn** [comment]
Fix it.  Thanks again for letting me know.
