### ISSUE TITLE
python3: can't open file 'print_binary.py'

### ISSUE THREAD

**Issue by benoitOpenBSD** [mikeakohn/naken_asm#80]
Hi,

When I try to "make tests", I have the following error :

...
[1802]testing req ... PASS
[1802]testing seq ... PASS
[1802]testing adci 14 ... head: 1802_naken.hex: No such file or directory
FAIL
  (exp) :020000007C0E74
  (got) 
python3: can't open file 'print_binary.py': [Errno 2] No such file or directory

I can't find the file print_binary.py in the git repository.

Best regards,
Benoit

**Comment by mikeakohn** [comment]
Whoops.  Never meant to check that in.  Should be fixed... let me know and I'll close the issue (or you can close it if you like).  Thanks for the heads up!

**Comment by benoitOpenBSD** [comment]
It's OK now, thanks !
